Watch Face UI
sanketshah92/WatchApplication pull request #5
Opened 2022-05-24 13:05 UTC by sanketshah92

- Adding Watchface project file 
- Designed watch face using samsung watch studio
- Added time & date text & app shortcut complication area.

2022-05-25 08:57 UTC, EntyR requested changes

2022-05-25 08:57 UTC, EntyR commented on .idea/vcs.xml
> +</project>
please, add all .idea folder into gitignore

2022-05-25 09:12 UTC, EntyR commented
It's not not possible to export watchfacestudio project into android studio as far as I know. Please specify watchface directly in your project, can check android studio new project templates for reference

2022-05-25 09:15 UTC, EntyR commented
Also where's no need to add any complications for now

2022-06-09 08:16 UTC, sanketshah92 commented
@EntyR i have updated WatchFace Service, do we need to use canvas to adjust background and draw texts for time and date? Please look into my approach.  I have used round shape image as a background, So for square watch it may be different look and feel.

2022-06-14 12:26 UTC, EntyR commented on app/src/main/java/com/sanket/watchapplication/presentation/watchface/MyWatchFace.kt
> +            val bitmap =
please move any declaration out from onDraw method also please make a check in the begining to verify if date value was changed

2022-06-14 12:28 UTC, EntyR commented on app/src/main/java/com/sanket/watchapplication/presentation/watchface/MyWatchFace.kt
> +        private val NORMAL_TYPEFACE = Typeface.create(Typeface.SANS_SERIF, Typeface.NORMAL)
please use roboco Typeface instead

2022-06-14 12:45 UTC, EntyR commented
> my approach. I have used round shape image as a background, So for square watch it may be different look and feel.

As for square devices no need to worry about them it's app only for round devices, still if you want it to display on square you can use gradient instead of loading image resources, something like this

`private val colors = intArrayOf(
                Color.BLACK,
                Color.BLACK,
                context.getColor(R.color.purple_primary),
                Color.BLACK,
            )
`
`
            val backgroundColor = SweepGradient(
                bounds.exactCenterX(),
                bounds.exactCenterY(),
                colors,
                null
            )`

2022-06-17 09:20 UTC, EntyR commented on app/src/main/java/com/sanket/watchapplication/presentation/watchface/MyWatchFace.kt
> +                Bitmap.createScaledBitmap(backgroundImageBitmap, canvas.width, canvas.height, true)
Please move it out of onDraw method

2022-06-17 09:30 UTC, EntyR commented on app/src/main/java/com/sanket/watchapplication/presentation/watchface/MyWatchFace.kt
> +             val timeText = LocalTime.now().format(DateTimeFormatter.ofPattern(WATCHFACE_TIME_FORMAT))
Same thing here

2022-06-17 13:29 UTC, sanketshah92 commented on app/src/main/java/com/sanket/watchapplication/presentation/watchface/MyWatchFace.kt
> +                Bitmap.createScaledBitmap(backgroundImageBitmap, canvas.width, canvas.height, true)
done

2022-06-17 13:29 UTC, sanketshah92 commented on app/src/main/java/com/sanket/watchapplication/presentation/watchface/MyWatchFace.kt
> +             val timeText = LocalTime.now().format(DateTimeFormatter.ofPattern(WATCHFACE_TIME_FORMAT))
done

2022-06-17 13:29 UTC, sanketshah92 commented on app/src/main/java/com/sanket/watchapplication/presentation/watchface/MyWatchFace.kt
> +        private val NORMAL_TYPEFACE = Typeface.create(Typeface.SANS_SERIF, Typeface.NORMAL)
done

2022-06-17 13:29 UTC, sanketshah92 commented on app/src/main/java/com/sanket/watchapplication/presentation/watchface/MyWatchFace.kt
> +            val bitmap =
done

2022-06-21 07:55 UTC, AlexeyKolosov approved these changes

2022-06-21 07:57 UTC, AlexeyKolosov commented
I can see a lot of changes, which are not related to Watch Face UI, it is bad, please in future separate pull requests. Let's merge this.

2022-06-21 11:06 UTC, merged