Watch 04- Measure Heart Rate UI
sanketshah92/WatchApplication pull request #7
Opened 2022-05-26 06:09 UTC by sanketshah92

- Design heart rate measure screen
- Adding animations for start listening
- Adding graph path to navigate from main menu to measure heart rate.

2022-05-26 08:57 UTC, EntyR requested changes

2022-05-26 08:57 UTC, EntyR commented on app/src/main/java/com/sanket/watchapplication/presentation/measureHR/MeasureHeartRateFragment.kt
> +        btnStart.visibility = View.VISIBLE
Please use view binding

2022-05-26 08:57 UTC, EntyR commented on app/src/main/res/drawable/rounded_bg_button.xml
> +            <corners android:radius="24dp" />
Please extract resources

2022-05-26 08:57 UTC, EntyR commented on app/src/main/res/layout/fragment_measure_hr.xml
> +        android:layout_width="72dp"
Please extract all resources

2022-05-26 09:12 UTC, EntyR commented
![image](https://user-images.githubusercontent.com/89445868/170454982-338a17f9-0813-40e3-b785-fabbfba485e0.png)

The background is from figma. You doesn't have to make it pixel by pixel but please make them similar. Also ask me if you need any background for ui debuging since you don't have access to figma, just put it as background for root element.

Animation is very nice! Still you will need to display real value there. It will be great if you could animate real value with custom view or something but you don't have what much time so can make it as simple chart and use some chart library like [this ](https://github.com/PhilJay/MPAndroidChart).

2022-05-26 09:16 UTC, EntyR commented
Also I forgot to mention font used in app. I sent it as email. Please change it here and in other request

2022-05-31 17:16 UTC, sanketshah92 commented
> Also I forgot to mention font used in app. I sent it as email. Please change it here and in other request

done

2022-05-31 17:16 UTC, sanketshah92 commented
> ![image](https://user-images.githubusercontent.com/89445868/170454982-338a17f9-0813-40e3-b785-fabbfba485e0.png)
> 
> The background is from figma. You doesn't have to make it pixel by pixel but please make them similar. Also ask me if you need any background for ui debuging since you don't have access to figma, just put it as background for root element.
> 
> Animation is very nice! Still you will need to display real value there. It will be great if you could animate real value with custom view or something but you don't have what much time so can make it as simple chart and use some chart library like [this ](https://github.com/PhilJay/MPAndroidChart).

fixed

2022-05-31 17:17 UTC, sanketshah92 commented on app/src/main/res/layout/fragment_measure_hr.xml
> +        android:layout_width="72dp"
done

2022-05-31 17:17 UTC, sanketshah92 commented on app/src/main/res/drawable/rounded_bg_button.xml
> +            <corners android:radius="24dp" />
done

2022-06-17 13:29 UTC, merged